# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .llm_predictor_details import LlmPredictorDetails
from .predictor_details import PredictorDetails


class DetailsUnion_Base(PredictorDetails):
    type: typing_extensions.Literal["base"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


class DetailsUnion_Llm(LlmPredictorDetails):
    type: typing_extensions.Literal["llm"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


DetailsUnion = typing.Union[DetailsUnion_Base, DetailsUnion_Llm]
