/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../../../errors";
import * as GlooApi from "../../..";
export declare class NotAuthorized extends errors.GlooApiError {
    constructor(body: GlooApi.MessageBody);
}
