/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../../../environments";
import * as core from "../../../../../../core";
import * as Gloo from "../../../../..";
export declare namespace Classification {
    interface Options {
        environment?: core.Supplier<environments.GlooEnvironment | string>;
        token: core.Supplier<core.BearerToken>;
        xGlooTag?: core.Supplier<string | undefined>;
        xGlooOrg?: core.Supplier<string | undefined>;
    }
}
export declare class Classification {
    protected readonly _options: Classification.Options;
    constructor(_options: Classification.Options);
    predict(classifierId: string, request: Gloo.v1.PredictionRequest): Promise<Gloo.v1.PredictionResponse>;
    protected _getAuthorizationHeader(): Promise<string>;
}
