/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../..";
import * as GlooApi from "../../../../../../api";
import * as core from "../../../../../../core";
export declare const FeedbackType: core.serialization.Schema<serializers.v1.FeedbackType.Raw, GlooApi.v1.FeedbackType>;
export declare namespace FeedbackType {
    type Raw = "ATLEAST_ONE_CORRECT" | "ALL_CORRECT" | "NONE_CORRECT" | "UNKNOWN";
}
