/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../..";
import * as GlooApi from "../../../../../../api";
import * as core from "../../../../../../core";
export declare const InternalPredictRequest: core.serialization.ObjectSchema<serializers.v1.InternalPredictRequest.Raw, GlooApi.v1.InternalPredictRequest>;
export declare namespace InternalPredictRequest {
    interface Raw {
        input: serializers.v1.InternalPredictInput.Raw;
        llm_target?: string | null;
        configuration?: serializers.v1.Configuration.Raw | null;
        override?: serializers.v1.ConfigurationOverride.Raw | null;
    }
}
