/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../..";
import * as GlooApi from "../../../../../../api";
import * as core from "../../../../../../core";
export declare const InternalPredictResponseBase: core.serialization.ObjectSchema<serializers.v1.InternalPredictResponseBase.Raw, GlooApi.v1.InternalPredictResponseBase>;
export declare namespace InternalPredictResponseBase {
    interface Raw {
        selected_classes: serializers.v1.SelectedClass.Raw[];
        predictor_details: serializers.v1.DetailsUnion.Raw[];
    }
}
