/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../..";
import * as GlooApi from "../../../../../../api";
import * as core from "../../../../../../core";
export declare const InternalGenerateTextRequest: core.serialization.ObjectSchema<serializers.v1.InternalGenerateTextRequest.Raw, GlooApi.v1.InternalGenerateTextRequest>;
export declare namespace InternalGenerateTextRequest {
    interface Raw {
        llm_target: string;
        num_samples: number;
        prompt: string;
    }
}
