/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../..";
import * as GlooApi from "../../../../../../api";
import * as core from "../../../../../../core";
export declare const KlassSelection: core.serialization.ObjectSchema<serializers.v1.KlassSelection.Raw, GlooApi.v1.KlassSelection>;
export declare namespace KlassSelection {
    interface Raw {
        available: serializers.v1.Klass.Raw[];
        supressed: string[];
    }
}
