/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../..";
import * as GlooApi from "../../../../../../api";
import * as core from "../../../../../../core";
export declare const PredictorKlassDetails: core.serialization.ObjectSchema<serializers.v1.PredictorKlassDetails.Raw, GlooApi.v1.PredictorKlassDetails>;
export declare namespace PredictorKlassDetails {
    interface Raw {
        klass_id: string;
        klass_version: number;
        klass_name: string;
        klass_description: string;
        selected: boolean;
        confidence: number;
    }
}
