/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../..";
import * as GlooApi from "../../../../../../api";
import * as core from "../../../../../../core";
export declare const Status: core.serialization.Schema<serializers.v1.Status.Raw, GlooApi.v1.Status>;
export declare namespace Status {
    type Raw = "PASS" | "FAIL" | "FAIL_PARENT";
}
