/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../..";
import * as GlooApi from "../../../../../../api";
import * as core from "../../../../../../core";
export declare const TraditionalPredictor: core.serialization.Schema<serializers.v1.TraditionalPredictor.Raw, GlooApi.v1.TraditionalPredictor>;
export declare namespace TraditionalPredictor {
    type Raw = TraditionalPredictor.Id | TraditionalPredictor.Override;
    interface Id {
        type: "id";
        value: string;
    }
    interface Override extends serializers.v1.TraditionalPredictorOverride.Raw {
        type: "override";
    }
}
