/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../../../environments";
import * as core from "../../../../../../core";
import * as GlooApi from "../../../../..";
export declare namespace Classification {
    interface Options {
        environment?: core.Supplier<environments.GlooApiEnvironment | string>;
        token: core.Supplier<core.BearerToken>;
        xGlooTag?: core.Supplier<string | undefined>;
        xGlooOrg?: core.Supplier<string | undefined>;
        fetcher?: core.FetchFunction;
    }
}
export declare class Classification {
    protected readonly _options: Classification.Options;
    constructor(_options: Classification.Options);
    predict(classifierId: string, request: GlooApi.v1.PredictionRequest): Promise<GlooApi.v1.PredictionResponse>;
    predictInternal(classifierId: string, request: GlooApi.v1.InternalPredictRequest): Promise<GlooApi.v1.InternalPredictResponse>;
    feedback(classifierId: string, request: GlooApi.v1.ClassificationFeedbackRequest): Promise<void>;
    generateTextInternal(classifierId: string, request: GlooApi.v1.InternalGenerateTextRequest): Promise<GlooApi.v1.InternalGenerateTextResponse>;
    protected _getAuthorizationHeader(): Promise<string>;
}
