/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../..";
import * as Gloo from "../../../../../../api";
import * as core from "../../../../../../core";
export declare const LlmPredictorDetails: core.serialization.ObjectSchema<serializers.v1.LlmPredictorDetails.Raw, Gloo.v1.LlmPredictorDetails>;
export declare namespace LlmPredictorDetails {
    interface Raw extends serializers.v1.PredictorDetails.Raw {
        hallucinations: string[];
        tokens_used: number;
        reasoning: string;
    }
}
