/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../..";
import * as Gloo from "../../../../../../api";
import * as core from "../../../../../../core";
export declare const PredictionRequest: core.serialization.ObjectSchema<serializers.v1.PredictionRequest.Raw, Gloo.v1.PredictionRequest>;
export declare namespace PredictionRequest {
    interface Raw {
        llm_target?: string | null;
        text: string;
        tags?: string[] | null;
        configuration?: serializers.v1.Configuration.Raw | null;
    }
}
