/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../..";
import * as Gloo from "../../../../../../api";
import * as core from "../../../../../../core";
export declare const PredictorDetails: core.serialization.ObjectSchema<serializers.v1.PredictorDetails.Raw, Gloo.v1.PredictorDetails>;
export declare namespace PredictorDetails {
    interface Raw {
        predictor_id: string;
        predictor_type: serializers.v1.PredictorType.Raw;
        status: serializers.v1.Status.Raw;
        latency_ms: number;
        classes: serializers.v1.PredictorKlassDetails.Raw[];
    }
}
