/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../..";
import * as Gloo from "../../../../../../api";
import * as core from "../../../../../../core";
export declare const SelectedClass: core.serialization.ObjectSchema<serializers.v1.SelectedClass.Raw, Gloo.v1.SelectedClass>;
export declare namespace SelectedClass {
    interface Raw {
        id: string;
        latest_version: number;
        latest_name: string;
        overall_confidence: number;
    }
}
