/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "./environments";
import * as core from "./core";
import { Classifiers } from "./api/resources/classifiers/client/Client";
import { V1 } from "./api/resources/v1/client/Client";
export declare namespace GlooApiClient {
    interface Options {
        environment?: core.Supplier<environments.GlooApiEnvironment | string>;
        token: core.Supplier<core.BearerToken>;
        xGlooTag?: core.Supplier<string | undefined>;
        xGlooOrg?: core.Supplier<string | undefined>;
        fetcher?: core.FetchFunction;
    }
}
export declare class GlooApiClient {
    protected readonly _options: GlooApiClient.Options;
    constructor(_options: GlooApiClient.Options);
    protected _classifiers: Classifiers | undefined;
    get classifiers(): Classifiers;
    protected _v1: V1 | undefined;
    get v1(): V1;
}
