"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GlooApiClient = void 0;
const Client_1 = require("./api/resources/classifiers/client/Client");
const Client_2 = require("./api/resources/v1/client/Client");
class GlooApiClient {
    constructor(_options) {
        this._options = _options;
    }
    get classifiers() {
        var _a;
        return ((_a = this._classifiers) !== null && _a !== void 0 ? _a : (this._classifiers = new Client_1.Classifiers(this._options)));
    }
    get v1() {
        var _a;
        return ((_a = this._v1) !== null && _a !== void 0 ? _a : (this._v1 = new Client_2.V1(this._options)));
    }
}
exports.GlooApiClient = GlooApiClient;
