/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const GlooApiEnvironment: {
    readonly Production: "https://api.trygloo.com";
    readonly Localhost: "http://localhost:8080";
};
export declare type GlooApiEnvironment = typeof GlooApiEnvironment.Production | typeof GlooApiEnvironment.Localhost;
