# This file was auto-generated by Fern from our API Definition.

import typing

from .environment import GlooApiEnvironment
from .resources.v_1.client import AsyncV1Client, V1Client


class GlooApi:
    def __init__(
        self,
        *,
        environment: GlooApiEnvironment = GlooApiEnvironment.PRODUCTION,
        x_gloo_tag: typing.Optional[str] = None,
        x_gloo_org: typing.Optional[str] = None,
        token: str
    ):
        self._environment = environment
        self.x_gloo_tag = x_gloo_tag
        self.x_gloo_org = x_gloo_org
        self._token = token
        self.v_1 = V1Client(
            environment=self._environment, x_gloo_tag=self.x_gloo_tag, x_gloo_org=self.x_gloo_org, token=self._token
        )


class AsyncGlooApi:
    def __init__(
        self,
        *,
        environment: GlooApiEnvironment = GlooApiEnvironment.PRODUCTION,
        x_gloo_tag: typing.Optional[str] = None,
        x_gloo_org: typing.Optional[str] = None,
        token: str
    ):
        self._environment = environment
        self.x_gloo_tag = x_gloo_tag
        self.x_gloo_org = x_gloo_org
        self._token = token
        self.v_1 = AsyncV1Client(
            environment=self._environment, x_gloo_tag=self.x_gloo_tag, x_gloo_org=self.x_gloo_org, token=self._token
        )
