"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.V1 = void 0;
const Client_1 = require("../resources/classification/client/Client");
class V1 {
    constructor(_options) {
        this._options = _options;
    }
    get classification() {
        var _a;
        return ((_a = this._classification) !== null && _a !== void 0 ? _a : (this._classification = new Client_1.Classification(this._options)));
    }
}
exports.V1 = V1;
