/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { Classification } from "../resources/classification/client/Client";
export declare namespace V1 {
    interface Options {
        environment?: core.Supplier<environments.GlooEnvironment | string>;
        token: core.Supplier<core.BearerToken>;
        xGlooTag?: core.Supplier<string | undefined>;
        xGlooOrg?: core.Supplier<string | undefined>;
    }
}
export declare class V1 {
    protected readonly _options: V1.Options;
    constructor(_options: V1.Options);
    protected _classification: Classification | undefined;
    get classification(): Classification;
}
