/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as GlooApi from "../../../../api";
import * as core from "../../../../core";
export declare const ClassificationFeedbackRequest: core.serialization.ObjectSchema<serializers.ClassificationFeedbackRequest.Raw, GlooApi.ClassificationFeedbackRequest>;
export declare namespace ClassificationFeedbackRequest {
    interface Raw {
        request_token: string;
        correctness_status?: serializers.CorrectnessStatus.Raw | null;
        expected_classes?: string[] | null;
    }
}
