/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as serializers from "../../..";
import * as GlooApi from "../../../../api";
export declare const ClassificationRequest: core.serialization.Schema<serializers.ClassificationRequest.Raw, GlooApi.ClassificationRequest>;
export declare namespace ClassificationRequest {
    type Raw = ClassificationRequest.Text | ClassificationRequest.Thread;
    interface Text extends _Base, serializers.TextInput.Raw {
        type: "text";
    }
    interface Thread extends _Base, serializers.ThreadInput.Raw {
        type: "thread";
    }
    interface _Base {
        enable_low_latency?: boolean | null;
        language_hint?: string | null;
    }
}
