/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as GlooApi from "../../../../api";
import * as core from "../../../../core";
export declare const MessageType: core.serialization.Schema<serializers.MessageType.Raw, GlooApi.MessageType>;
export declare namespace MessageType {
    type Raw = "USER" | "AGENT";
}
