/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as GlooApi from "../../../../api";
import * as core from "../../../../core";
export declare const ThreadInput: core.serialization.ObjectSchema<serializers.ThreadInput.Raw, GlooApi.ThreadInput>;
export declare namespace ThreadInput {
    interface Raw {
        topic?: string | null;
        summary?: string | null;
        messages: serializers.Message.Raw[];
    }
}
