/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type FeedbackType = "ATLEAST_ONE_CORRECT" | "ALL_CORRECT" | "NONE_CORRECT" | "UNKNOWN";
export declare const FeedbackType: {
    readonly AtleastOneCorrect: "ATLEAST_ONE_CORRECT";
    readonly AllCorrect: "ALL_CORRECT";
    readonly NoneCorrect: "NONE_CORRECT";
    readonly Unknown: "UNKNOWN";
};
