/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as GlooApi from "../../../../..";
export interface InternalPredictResponse extends GlooApi.v1.InternalPredictResponseBase {
    status: GlooApi.v1.Status;
    latencyMs: number;
    normalizer?: GlooApi.v1.NormalizerResponse;
}
