/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as GlooApi from "../../../../..";
export declare type LlmPredictor = GlooApi.v1.LlmPredictor.Id | GlooApi.v1.LlmPredictor.Override;
export declare namespace LlmPredictor {
    interface Id {
        type: "id";
        value: string;
    }
    interface Override extends GlooApi.v1.LlmPredictorOverride {
        type: "override";
    }
}
