/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as GlooApi from "../../../../..";
export interface LlmPredictorOptions {
    failureMode: GlooApi.v1.FailureMode;
    llmConfig: GlooApi.v1.LlmConfig;
    inputDescription: string;
    objective: string;
    skipPriorAvailableKlasses: boolean;
    addPriorSelectedKlasses: boolean;
}
