/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as GlooApi from "../../../../..";
export interface PredictionResponse extends GlooApi.v1.InternalPredictResponseBase {
    id: string;
}
