/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type PredictorType = "FT" | "LLM";
export declare const PredictorType: {
    readonly Ft: "FT";
    readonly Llm: "LLM";
};
