/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface SelectedClass {
    id: string;
    latestVersion: number;
    latestName: string;
    /** Some complicated rule */
    overallConfidence: number;
}
