/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type Status = "PASS" | "FAIL" | "FAIL_PARENT";
export declare const Status: {
    readonly Pass: "PASS";
    readonly Fail: "FAIL";
    readonly FailParent: "FAIL_PARENT";
};
