/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Gloo from "../../../../..";
export declare type DetailsUnion = Gloo.v1.DetailsUnion.Base | Gloo.v1.DetailsUnion.Llm;
export declare namespace DetailsUnion {
    interface Base extends Gloo.v1.PredictorDetails {
        type: "base";
    }
    interface Llm extends Gloo.v1.LlmPredictorDetails {
        type: "llm";
    }
}
