/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Gloo from "../../../../..";
export interface LlmPredictorDetails extends Gloo.v1.PredictorDetails {
    hallucinations: string[];
    tokensUsed: number;
    reasoning: string;
}
