/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface PredictorKlassDetails {
    klassId: string;
    klassVersion: number;
    klassName: string;
    klassDescription: string;
    selected: boolean;
    /** The confidence of the prediction (0 - 1). */
    confidence: number;
}
