/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Gloo from "../../../../..";
export interface PredictorDetails {
    predictorId: string;
    predictorType: Gloo.v1.PredictorType;
    status: Gloo.v1.Status;
    latencyMs: number;
    classes: Gloo.v1.PredictorKlassDetails[];
}
