/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Gloo from "../../../../..";
export interface PredictionResponse extends Gloo.v1.InternalPredictResponseBase {
    id: string;
}
