# This file was auto-generated by Fern from our API Definition.

import typing

from ...environment import GlooApiEnvironment
from .resources.classification.client import AsyncClassificationClient, ClassificationClient


class V1Client:
    def __init__(
        self,
        *,
        environment: GlooApiEnvironment = GlooApiEnvironment.PRODUCTION,
        x_gloo_tag: typing.Optional[str] = None,
        x_gloo_org: typing.Optional[str] = None,
        token: str
    ):
        self._environment = environment
        self.x_gloo_tag = x_gloo_tag
        self.x_gloo_org = x_gloo_org
        self._token = token
        self.classification = ClassificationClient(
            environment=self._environment, x_gloo_tag=self.x_gloo_tag, x_gloo_org=self.x_gloo_org, token=self._token
        )


class AsyncV1Client:
    def __init__(
        self,
        *,
        environment: GlooApiEnvironment = GlooApiEnvironment.PRODUCTION,
        x_gloo_tag: typing.Optional[str] = None,
        x_gloo_org: typing.Optional[str] = None,
        token: str
    ):
        self._environment = environment
        self.x_gloo_tag = x_gloo_tag
        self.x_gloo_org = x_gloo_org
        self._token = token
        self.classification = AsyncClassificationClient(
            environment=self._environment, x_gloo_tag=self.x_gloo_tag, x_gloo_org=self.x_gloo_org, token=self._token
        )
