/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "./environments";
import * as core from "./core";
import { V1 } from "./api/resources/v1/client/Client";
export declare namespace GlooClient {
    interface Options {
        environment?: core.Supplier<environments.GlooEnvironment | string>;
        token: core.Supplier<core.BearerToken>;
        xGlooTag?: core.Supplier<string | undefined>;
        xGlooOrg?: core.Supplier<string | undefined>;
    }
}
export declare class GlooClient {
    protected readonly _options: GlooClient.Options;
    constructor(_options: GlooClient.Options);
    protected _v1: V1 | undefined;
    get v1(): V1;
}
