"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GlooClient = void 0;
const Client_1 = require("./api/resources/v1/client/Client");
class GlooClient {
    constructor(_options) {
        this._options = _options;
    }
    get v1() {
        var _a;
        return ((_a = this._v1) !== null && _a !== void 0 ? _a : (this._v1 = new Client_1.V1(this._options)));
    }
}
exports.GlooClient = GlooClient;
