"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GlooEnvironment = void 0;
exports.GlooEnvironment = {
    Production: "https://api.trygloo.com",
    Localhost: "http://localhost:8080",
};
