/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const GlooEnvironment: {
    readonly Production: "https://api.trygloo.com";
    readonly Localhost: "http://localhost:8080";
};
export declare type GlooEnvironment = typeof GlooEnvironment.Production | typeof GlooEnvironment.Localhost;
